############################
## CHANGE THESE
############################

baseURL: "https://DatWins.github.io/testing_qubttemplate"
title: testing_qubttemplate

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
